name: Build & Push Player360 Web Container

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-web:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build web image
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/player360-web:latest"
          docker build -t $IMAGE .

      - name: Push web image
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/player360-web:latest"
          docker push $IMAGE
